---
services:
  esphome:
    image: ghcr.io/esphome/esphome
    container_name: esphome
    ports:
    - "6052:6052"
    volumes:
    - ./device-files:/config
    environment:
    - ESPHOME_DASHBOARD_USE_PING=true
