esphome:
  name: rain-water
  friendly_name: Rain Water Control

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: fkJhRpwgek++AqTKS5LQoHSpHmeRaJEhtg0Ea/CQ6UA=

ota:
  - platform: esphome
    password: fkJhRpwgek++AqTKS5LQoHSpHmeRaJEhtg0Ea/CQ6UA=

wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Rain Water Fallback Hotspot"
    password: "sYV2nSM4hvus"

binary_sensor:
- platform: gpio
  name: "Garage Roof Rain and Snow Sensor"
  icon: "mdi:weather-snowy-rainy"
  pin:
    number: 19
    inverted: false
    mode:
      input: true
      pullup: true

switch:
- platform: gpio
  name: "Water Butt Output Valve"
  icon: "mdi:pipe-valve"
  pin:
    number: 16
    inverted: false
